# Dependencies
markdown:         redcarpet
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Akshay Mohite
tagline:          Personal Ramblings of a Developer!
description:      'Developer <a href="https://bigbinary.com" target="_blank">@bigbinary</a>. Blog at <a href="https://rubyinrails.com" target="_blank">@RubyInRails</a>. Ruby on Rails Enthusiast. Love Remove Working!'
url:              http://mohiteakshay.com
baseurl:          /

author:
  name:           'Akshay Mohite'
  url:            https://twitter.com/akshaymohite31

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/akshaymohite
gems:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-feed
  - redcarpet
  - rouge
